maxcountryman/tower-sessions

CHANGELOG.md
src/cookie_config.rs
src/session.rs

This is a breaking change that moves the expiration time into the inner
state and thus makes it settable from applications that might consume
sessions.
Here we've removed `with_max_age`, and replaced it with two new methods,
`set_expiration_time` and `set_expiration_time_from_max_age` as well as
added an optional expiration time to the session's new method.
Doing so helps us reduce confusion given `with_max_age` is already used
by the service module for a different but related purpose.
Note that creating a session via its default implementation will yield
the same semantics as before.
Closes https://github.com/maxcountryman/tower-sessions/issues/7.

rework session expiration time management

---

.github/workflows/rust.yml
Cargo.toml
examples/moka-postgres-store.rs
src/lib.rs
src/moka_store.rs
src/service.rs
src/session.rs
src/session_store.rs
tests/moka-store-integration-tests.rs
tests/moka-store-sqlite-integration-tests.rs

This implements `CachingSessionStore`, which holds two `SessionStore`s. One acts as a frontend cache, while the other asks as the backend persistence store.
Anything that implements `SessionStore` may be used as either the cache or the store.
We also refactor our Moka implementation as it can now be used for layered caching directly in via `CachingSessionStore`.

layered caching for session stores

---

README.md

Following up on: https://github.com/maxcountryman/tower-sessions/discussions/17

README: production notes, db(s) cleaning

---

src/service.rs
src/session.rs
tests/common/mod.rs

When a session is empty it should be removed entirely.
Previously this was not the case as the modified flag cannot be set when the underlying session data is empty. This makes sense because an empty session should not be updated but instead deleted.
However, this also meant that removing the last key of a previously stored session would not reflect this update in the store--the session would not be saved to the store or deleted.
To address this, we now look for an empty session after resolving the request. When found, we delete the session from the store and return the response.
Fixes #21.

ensure sessions are deleted when empty

---

CHANGELOG.md
Cargo.toml
README.md
src/mongodb_store.rs
src/service.rs
src/sqlx_store/mysql_store.rs
src/sqlx_store/postgres_store.rs
src/sqlx_store/sqlite_store.rs

This is a temporary fix for a data race that occurs when a session is saved and loaded at the same time. The result of this race is that stale data can be loaded into memory, resulting in potential data loss where multiple requests using the same session are issued simultaneously.
Here we address this by holding a lock for the duration of the request. This solution is only temporary, as the underlying session implementation can instead be modified to ensure safe access between the save and load await points.
This supercedes #35.

fix session saving and loading data race

---

Cargo.toml
src/lib.rs
src/mongodb_store.rs
src/service.rs
src/session.rs
src/sqlx_store/mysql_store.rs
src/sqlx_store/postgres_store.rs
src/sqlx_store/sqlite_store.rs

This moves to a pattern of tracking loaded sessions via a hash set. By doing so, we can share sessions concurrently. In other words, we no longer need a lock to protect the session for the duration of the request and instead are able to share sessions between concurrent tasks.
Why do we need this at all? A data race can otherwise occur when a session has been loaded but its modifications have not been stored. For instance, another task may load the session from the store in the meantime and this load will overwrite pending modifications as it will effectively replace the session in memory.
One solution to this problem is to lock the request, as we've done in a stopgap capacity. This unscalable at present and even when refined, i.e. to lock per session as opposed for all sessions, limits …

track loaded sessions to enable concurrent access

---

.github/workflows/rust.yml
Cargo.toml
examples/counter-concurrent.rs
src/service.rs
tests/concurrency-tests.rs

Here we implement a basic reference counting strategy to allow removal of loaded sessions.
Tracking loaded sessions in this way is necessary to support concurrent session access. For example, if we load from a store in order to provide a session as a request extension, this will load stale data. This happens when concurrently the same session is being modified. In other words, stale data can overwrite the session before its been persisted to the store.
To prevent this without losing the ability to concurrently operate over a session we manage shared memory via a map. When we load a session we also insert this session into the map of loaded sessions. Future requests will first try to read from the map before falling back to the store.
Problematically this map will grow indefinitely, since …

remove loaded sessions when unneeded

---

.github/workflows/rust.yml
Cargo.toml
examples/diesel-store-with-custom-table.rs
examples/diesel-store.rs
src/diesel_store.rs
src/lib.rs
tests/integration-tests.rs

This commit adds a custom diesel backed session store. It abstracts over different database backends and allows to customize the used session table.
This partially addresses #26 (the diesel part, not the diesel-async part)

Add a customizable diesel backed session store

---

Cargo.toml
examples/counter-concurrent.rs
examples/counter-extractor.rs
examples/counter.rs
examples/diesel-store-with-custom-table.rs
examples/diesel-store.rs
examples/moka-postgres-store.rs
examples/mongodb-store.rs
examples/mysql-store.rs
examples/postgres-store.rs
examples/redis-store.rs
examples/sqlite-store.rs
examples/strongly-typed.rs
src/cookie_config.rs
src/diesel_store.rs
src/lib.rs
src/memory_store.rs
src/moka_store.rs
src/mongodb_store.rs
src/redis_store.rs
src/service.rs
src/session.rs
src/session_store.rs
src/sqlx_store/mysql_store.rs
src/sqlx_store/postgres_store.rs
src/sqlx_store/sqlite_store.rs
tests/common/mod.rs
tests/integration-tests.rs

Here we rework how session expiration works, implementing a new type, `SessionExpiry` (later to be renamed `Expiry`). This enum defines three possible types of expiry,
1. Activity durations, i.e. durations for which the session will be renewed until inactivity for that duration has elapsed,
2. Absolute expirations, i.e. timestamps at which the session will expire regardless of activity,
3. And browser sessions, which are sessions that are valid for so long as the client remains open or the default threshold (two weeks) is reached.
Several breaking changes are required to make this change and importantly, the session itself is now serialized to the session store. This also means we no longer need `SessionRecord` and it has been removed entirely.
Please note that fields and methods related …

provide session expiration a la django

---

.github/workflows/rust.yml
Cargo.toml
examples/counter-concurrent.rs
examples/counter-extractor.rs
examples/counter.rs
examples/diesel-store-with-custom-table.rs
examples/diesel-store.rs
examples/moka-postgres-store.rs
examples/mongodb-store.rs
examples/mysql-store.rs
examples/postgres-store.rs
examples/redis-store.rs
examples/sqlite-store.rs
examples/strongly-typed.rs
src/cookie_config.rs
src/diesel_store.rs
src/lib.rs
src/memory_store.rs
src/moka_store.rs
src/mongodb_store.rs
src/redis_store.rs
src/service.rs
src/session.rs
src/session_store.rs
src/sqlx_store.rs
src/sqlx_store/mysql_store.rs
src/sqlx_store/postgres_store.rs
src/sqlx_store/sqlite_store.rs
tests/common/mod.rs
tests/integration-tests.rs

Here we remove the session-prefix from types that already reside in the session module.

drop session-prefix from session types

---

.github/workflows/rust.yml
src/memory_store.rs
src/moka_store.rs
src/service.rs

Following along with the Django approach, we push the responsibility of defining an active session semantic down to the stores themselves. Most stores already filter results based on e.g. the expiry date, but with this change we allow that semantic to be defined however implementors might like.
Provided stores that did not already do their own filtering have been updated to account for this change.

push active filtering down to stores

---

src/service.rs
src/session.rs

Now that the session is serialized to the storage backend, we also need to ensure that we reset the lifecycle markers before saving back to the store.

ensure session lifecycle states are reset

---

src/session.rs

This addresses a bug revealed in #77, where `Max-Age` may be set to some negative value.
Here we address this by instead setting `Max-Age` to zero in cases where it would otherwise be a negative value. Doing so helps ensure the removal of expired session cookies.

ensure non-negative max-age

---

src/memory_store.rs
src/moka_store.rs

This fixes a bug revealed in #74 where `MemoryStore` and `MokaStore` were erroneously returning expired sessions. This happened because the expiry date was not persisted when the session was saved. To address this, we store the expiry date when saving the session.

ensure memory and moka store persist expiry

---

CHANGELOG.md
src/service.rs
tests/common/mod.rs

This helps avoid fingerprinting.
Closes #73.

use a default session name of "id"

---

sqlx-store/src/postgres_store.rs

This PR adds the missing builder methods allowing the user to set the table and schema name for the session table.

Allow setting up the table and schema name for postgres

---

Cargo.toml
README.md
examples/counter-extractor.rs
examples/counter.rs
examples/moka-postgres-store.rs
examples/mongodb-store.rs
examples/mysql-store.rs
examples/postgres-store.rs
examples/redis-store.rs
examples/sqlite-store.rs
examples/strongly-typed.rs
src/lib.rs
tests/common/mod.rs
tower-sessions-core/Cargo.toml
tower-sessions-core/src/service.rs

Closes https://github.com/maxcountryman/tower-sessions/pull/104.
---
I'd be happy to drop b5de6e55a4eb24e19540c4464ae7dae818351b90 -- it just made it easier for me to run the various tests and build the examples without needing to setup `pkg-config` and `openssl`.

Bump axum-core to 0.4.0, http to 0.1, tower-cookies to 0.10.0

---

examples/redis-store.rs
redis-store/src/lib.rs
tests/integration-tests.rs

Makes `RedisStore` generic over any type that implements fred's `KeysInterface` so either a `RedisClient` or `RedisPool` can be used.
Since `RedisPool` is generally preferred for most applications, I switched all examples and documentation to use `RedisPool`. But, existing code that used `RedisClient` will not fail to compile.
I also modified the integration test that tests `RedisStore` to use a `RedisPool`.
Fixes issue #92

Allow constructing a `RedisStore` from a `RedisPool`

---

README.md
examples/counter-extractor.rs
examples/counter.rs
examples/moka-postgres-store.rs
examples/mongodb-store.rs
examples/mysql-store.rs
examples/postgres-store.rs
examples/redis-store.rs
examples/sqlite-store.rs
examples/strongly-typed.rs
src/lib.rs
tests/common/mod.rs
tower-sessions-core/src/service.rs
tower-sessions-core/src/session.rs

This reworks the tower service such that we always return a response. In other words, the service becomes infallible. What this means is we no longer need to build an intermediary service that captures boxed errors when using this crate with axum.
One side effect of this is that we lose the ability to handle specific errors, such as the session save failing, via downcasting. Instead, the middleware will return a 500 response. To address this, we could extend this implementation to allow for an on error callback, which could take an error and return a response.
This is a breaking change which also removes two extraneous variants from the session error type:
- `MissingId`
- `MissingCookies`

make service infallible

---

src/service.rs
tests/common/mod.rs

Here we manually check the configured session expiry to ensure that we account for `Expires: Session`.
This follows the Django implementation.
See: https://github.com/django/django/blob/9c6d7b4a678b7bbc6a1a14420f686162ba9016f5/django/contrib/sessions/middleware.py#L48-L49

ensure expires session

---

src/service.rs
tests/common/mod.rs
tests/integration-tests.rs

This ensures that configured paths and domains are provided to the cookie managed by the underlying cookie jar.
Note that this has no bearing on deletion from stores, which handle removal regardless of this change.

manually set path and domain on removal

---

src/service.rs

Here we both improve the allocation footprint of the session config as well as make the session manager configuration interface more flexible via the use of copy-on-write.

improve session config allocation footprint

---

tower-sessions-core/src/session.rs

Here we've revisited our implementations of `Display` and `FromStr` for `Id` and updated them to leverage the stack via slices.
Technically this is a breaking change because we've also updated the `IdError`.

avoid heap allocations with session id

---

tower-sessions-core/Cargo.toml

Seems to me that the tokio test infra should be enabled by default when running `cargo test`.

Enable features that are needed to enable async unit tests.

---

.github/workflows/rust.yml
Cargo.toml
examples/signed.rs
src/lib.rs
src/service.rs

This provides session cookie signing and encryption via the feature flags, `signed` and `private` respectively.
Cryptographic treatment of the cookie value provides some additional properties that may be beneficial to an application's security posture. For example, while session keys are already composed of crytographically secure random values, and therefore exceedingly difficult for an attacker to guess, the addition of a cryptographic key presents another dimension an attacker must overcome in order to successfully guess a valid session.
Furthermore, while session stores may themselves be secured, e.g. via techniques like encryption at rest or session store implementors may provide measures to ensure plaintext values are not stored directly, signed or encrypted cookies again require …

session cookie signing and encryption

---

tests/common/mod.rs
tower-sessions-core/src/session.rs

This addresses a bug where using `set_expiry` after an expiry has been set would not update the underlying record and thus not update the actual cookie expiration.
Closes #174.

ensure `session.set_expiry` updates record

---

memory-store/src/lib.rs
src/lib.rs
tower-sessions-core/Cargo.toml
tower-sessions-core/src/session.rs
tower-sessions-core/src/session_store.rs

This patch introduces a new method, `create`, to the `SessionStore` trait to distinguish between creating a new session and updating an existing one. This distinction is crucial for mitigating the potential for session ID collisions.
Although the probability of session ID collisions is statistically low, given that IDs are composed of securely-random `i128` values, such collisions pose a significant security risk. A store that does not differentiate between session creation and updates could inadvertently allow an existing session to be accessed, leading to potential session takeovers.
To prevent this, stores must ensure the uniqueness of session IDs during creation. The new `create` method is designed to allow session store implementers to handle any conflicts and resolve them.
This …

Id collision mitigation

---

tower-sessions-core/src/session.rs

This fixes a bug where calling `cycle_id` would invoke the session store `save` method rather than the `create` method.
Because cycling the session ID involves creating a new ID, this must follow the same semantics as normal session creation. Therefore prior to this fix session ID collision could occur through this vector.

ensure id cycling invokes create

---

README.md
src/lib.rs

I created a session store that stores sessions in local files, similar to the default behavior in frameworks like Django and PHP. This adds it to the list of session stores.

add tower-sessions-file-store
